/**
 * @pelilauta/icons - Tier 1 Community MIT Icon Registry.
 */

export const icons = {
  add: new URL("./add.svg", import.meta.url).pathname,
  "arrow-down": new URL("./arrow-down.svg", import.meta.url).pathname,
  "arrow-up": new URL("./arrow-up.svg", import.meta.url).pathname,
  assets: new URL("./assets.svg", import.meta.url).pathname,
  avatar: new URL("./avatar.svg", import.meta.url).pathname,
  bubble: new URL("./bubble.svg", import.meta.url).pathname,
  card: new URL("./card.svg", import.meta.url).pathname,
  check: new URL("./check.svg", import.meta.url).pathname,
  "chevron-left": new URL("./chevron-left.svg", import.meta.url).pathname,
  clock: new URL("./clock.svg", import.meta.url).pathname,
  components: new URL("./components.svg", import.meta.url).pathname,
  compose: new URL("./compose.svg", import.meta.url).pathname,
  "copy-md": new URL("./copy-md.svg", import.meta.url).pathname,
  css: new URL("./css.svg", import.meta.url).pathname,
  delete: new URL("./delete.svg", import.meta.url).pathname,
  design: new URL("./design.svg", import.meta.url).pathname,
  dots: new URL("./dots.svg", import.meta.url).pathname,
  drag: new URL("./drag.svg", import.meta.url).pathname,
  edit: new URL("./edit.svg", import.meta.url).pathname,
  experiment: new URL("./experiment.svg", import.meta.url).pathname,
  "file-pdf": new URL("./file-pdf.svg", import.meta.url).pathname,
  filter: new URL("./filter.svg", import.meta.url).pathname,
  font: new URL("./font.svg", import.meta.url).pathname,
  fork: new URL("./fork.svg", import.meta.url).pathname,
  fox: new URL("./fox.svg", import.meta.url).pathname,
  idea: new URL("./idea.svg", import.meta.url).pathname,
  "import-export": new URL("./import-export.svg", import.meta.url).pathname,
  info: new URL("./info.svg", import.meta.url).pathname,
  kebab: new URL("./kebab.svg", import.meta.url).pathname,
  layout: new URL("./layout.svg", import.meta.url).pathname,
  login: new URL("./login.svg", import.meta.url).pathname,
  love: new URL("./love.svg", import.meta.url).pathname,
  mekanismi: new URL("./mekanismi.svg", import.meta.url).pathname,
  "open-down": new URL("./open-down.svg", import.meta.url).pathname,
  palette: new URL("./palette.svg", import.meta.url).pathname,
  pdf: new URL("./pdf.svg", import.meta.url).pathname,
  quote: new URL("./quote.svg", import.meta.url).pathname,
  reduce: new URL("./reduce.svg", import.meta.url).pathname,
  save: new URL("./save.svg", import.meta.url).pathname,
  share: new URL("./share.svg", import.meta.url).pathname,
  tools: new URL("./tools.svg", import.meta.url).pathname,
} as const;

export type IconNoun = keyof typeof icons;
