/**
 * generate-icon-registry.ts
 *
 * Reads SVG files from icon packages and generates typed TypeScript registries.
 * Run: node --experimental-strip-types scripts/generate-icon-registry.ts
 * Check: node --experimental-strip-types scripts/generate-icon-registry.ts --check
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

const HEADER = "// @generated by scripts/generate-icon-registry.ts — DO NOT EDIT\n";

interface RegistryConfig {
  svgDir: string;
  outFile: string;
  contentsPrefix: string;
}

const root = resolve(import.meta.dirname, "..");

const configs: RegistryConfig[] = [
  {
    svgDir: join(root, "packages/pelilauta-icons/src"),
    outFile: join(root, "packages/pelilauta-icons/src/index.ts"),
    contentsPrefix: "./",
  },
  {
    svgDir: join(root, "packages/myrrys-proprietary/icons"),
    outFile: join(root, "packages/myrrys-proprietary/index.ts"),
    contentsPrefix: "./icons/",
  },
];

function generate(config: RegistryConfig): string {
  const files = readdirSync(config.svgDir)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  const nouns = files.map((f) => basename(f, ".svg"));

  const nounType = nouns.map((n) => `  | ${JSON.stringify(n)}`).join("\n");

  const registryEntries = nouns
    .map((noun) => {
      let svg = readFileSync(join(config.svgDir, `${noun}.svg`), "utf-8");
      // Strip XML comments and excess whitespace to prevent toolchain noise (e.g. Illustrator timestamps)
      svg = svg.replace(/<!--[\s\S]*?-->/g, "").trim();
      return `  ${JSON.stringify(noun)}: ${JSON.stringify(svg)}`;
    })
    .join(",\n");

  const contentsEntries = nouns
    .map((noun) => {
      const key = `${config.contentsPrefix}${noun}.svg`;
      return `  ${JSON.stringify(key)}: _registry[${JSON.stringify(noun)}]`;
    })
    .join(",\n");

  return `${HEADER}
export type IconNoun =
${nounType};

const _registry: Record<IconNoun, string> = {
${registryEntries},
};

export const contents: Record<string, string> = {
${contentsEntries},
};

export function getIcon(noun: IconNoun | (string & {})): string | undefined {
  return _registry[noun as IconNoun];
}

export function getNouns(): IconNoun[] {
  return Object.keys(_registry) as IconNoun[];
}
`;
}

const isCheck = process.argv.includes("--check");
let stale = false;

for (const config of configs) {
  const generated = generate(config);

  if (isCheck) {
    let existing = "";
    try {
      existing = readFileSync(config.outFile, "utf-8");
    } catch {
      // File doesn't exist — definitely stale
    }
    if (existing !== generated) {
      console.error(`STALE: ${config.outFile}`);
      stale = true;
    } else {
      console.log(`OK: ${config.outFile}`);
    }
  } else {
    let existing = "";
    try {
      existing = readFileSync(config.outFile, "utf-8");
    } catch {
      // File doesn't exist
    }

    if (existing !== generated) {
      writeFileSync(config.outFile, generated, "utf-8");
      console.log(`Generated: ${config.outFile}`);
    } else {
      console.log(`Up to date: ${config.outFile}`);
    }
  }
}

if (isCheck && stale) {
  console.error("\nIcon registries are out of date. Run: pnpm gen:icons");
  process.exit(1);
}
